server:
  port: 5555
  
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.booking.system.hotel: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://hotel-service-discovery-server:8761/eureka/
  