version: "3"

services:
   #eureka server
   hotel-service-discovery-server:
      image: lucastoledo2010/hotel-service-discovery-server
      ports:
         - 8761:8761

   hotel-configuration-server:
      image: lucastoledo2010/hotel-configuration-server
      ports:
         - 8888:8888
      environment:
         EUREKASERVER_URI: "http://hotel-service-discovery-server:8761/eureka/"
         EUREKASERVER_PORT: "8761"
         ENCRYPT_KEY: "IMSYMMETRIC" #NOT SAFE - MAKE THIS PRIVATE REPOSITORY
  
   # The zipkin process services the UI, and also exposes a POST endpoint that
   # instrumentation can send trace data to. Scribe is enabled by default.
   zipkin:
      image: openzipkin/zipkin
      container_name: zipkin
      ports:
         - 9411:9411
      #environment:
         #- STORAGE_TYPE=mem
         # Uncomment to disable scribe
         # - SCRIBE_ENABLED=false
         # Uncomment to enable self-tracing
         # - SELF_TRACING_ENABLED=true
         # Uncomment to enable debug logging
         # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG
        
   
   hotel-gateway-service-server: #zuul server
      image: lucastoledo2010/hotel-gateway-service-server
      ports:
         - 5555:5555
      environment:
         PROFILE: "dev"
         SERVER_PORT: "5555" 
         CONFIGSERVER_URI: "http://hotel-configuration-server:8888"
         CONFIGSERVER_PORT: "8888"
         EUREKASERVER_URI: "http://hotel-service-discovery-server:8761/eureka/"
         EUREKASERVER_PORT: "8761"
         DATABASESERVER_PORT: "5432"
         ZIPKIN_URI: "http://zipkin:9411"
         ZIPKIN_PORT: "9411"

  
   database:
      image: postgres:9.5
      ports:
         - "5432:5432"
      volumes:
         - ./db-init-scripts:/docker-entrypoint-initdb.d
      environment:
         POSTGRES_USER: "postgres_dev"
         POSTGRES_PASSWORD: "p0stgr@s_dev" 
         POSTGRES_DB: "hotel_booking_system_dev"

   hotel-reservations-service:
      image: lucastoledo2010/hotel-reservations-service
      ports:
         - 8080:8080
      depends_on:
        - hotel-configuration-server
      environment:
          PROFILE: "dev"
          SERVER_PORT: "8080"
          CONFIGSERVER_URI: "http://hotel-configuration-server:8888"
          CONFIGSERVER_PORT:   "8888"
          EUREKASERVER_URI: "http://hotel-service-discovery-server:8761/eureka/"
          EUREKASERVER_PORT: "8761"
          DATABASESERVER_PORT: "5432"
          ENCRYPT_KEY: "IMSYMMETRIC" #NOT SAFE - MAKE THIS PRIVATE REPOSITORY
          ZIPKIN_URI: "http://zipkin:9411"
          ZIPKIN_PORT: "9411"
   
   hotel-rooms-service:
      image: lucastoledo2010/hotel-rooms-service
      ports:
         - 8085:8085
      depends_on:
        - hotel-configuration-server
      environment:
          PROFILE: "dev"
          SERVER_PORT: "8085"
          CONFIGSERVER_URI: "http://hotel-configuration-server:8888"
          CONFIGSERVER_PORT:   "8888"
          EUREKASERVER_URI: "http://hotel-service-discovery-server:8761/eureka/"
          EUREKASERVER_PORT: "8761"
          DATABASESERVER_PORT: "5432"
          ENCRYPT_KEY: "IMSYMMETRIC" #NOT SAFE - MAKE THIS PRIVATE REPOSITORY
          ZIPKIN_URI: "http://zipkin:9411"
          ZIPKIN_PORT: "9411"
   
   logspout: #send all logs to papertrail
      image: gliderlabs/logspout
      command: syslog://logs7.papertrailapp.com:31488
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
   
