version: "3"

services:

   hotel-configuration-server:
      image: lucastoledo2010/hotel-configuration-server
      ports:
         - 8888:8888

   hotel-reservations-service:
      image: lucastoledo2010/hotel-reservations-service
      ports:
         - 8080:8080
      depends_on:
        - hotel-configuration-server
      environment:
          PROFILE: "dev"
          CONFIGSERVER_URI: "http://hotel-configuration-server:8888"
          CONFIGSERVER_PORT:   "8888"
  