####
#Classpath and file-based solution
####

#server:
#   port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#     config:
#       server:
#           native:
#              searchLocations: classpath:config/,classpath:config/hotel-reservations-service

####
#   A configuraton service that uses a git-based repository to read the files from
####
server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true #register configuration server with service discovery eureka server
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/lucastoledo/hotel-booking-system-config-repo/
          searchPaths: hotel-reservations-service, hotel-rooms-service, hotel-gateway-service-server
          username: native-cloud-apps #basic authentication #NOT SAFE - MAKE THIS PRIVATE REPOSITORY
          password: 0ffended #basic authentication #NOT SAFE - MAKE THIS PRIVATE REPOSITORY