FROM openjdk:8u131-jre-alpine

MAINTAINER Lucas Toledo "lucas@someRandomEmailAddress.com"

COPY maven/hotel-reservations-service.jar hotel-reservations-service.jar

EXPOSE 8080

CMD ["java", "-jar","hotel-reservations-service.jar"]
